import type { NextPage } from "next";
import Head from "next/head";
import { Box, Text } from "@chakra-ui/react";
import Header from "../components/shared/Header";
import { useUserContext } from "../hooks/useUserContext";

const Home: NextPage = () => {
  const { user } = useUserContext();
  console.log(user);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box as="main">
        <Header />
        <Box as="section" p="1rem 3rem" minH="100vh"></Box>
        <Box p="3rem 3rem 0" fontSize="0.8rem">
          <Box as="footer" color="blackAlpha.500" borderTop="1px solid" borderColor="gray.300" p="1rem 0 2rem">
            <Text userSelect="none">2022 Chat. All rights reserved.</Text>
          </Box>
        </Box>
      </Box>
    </>
  );
};

export default Home;
